CREATE TABLE Submission (
code TEXT NOT NULL,
category INTEGER  ,
user_level INTEGER  ,
descriptive_title INTEGER NOT NULL ,
description TEXT NOT NULL,
email TEXT NOT NULL ,
student_name TEXT NOT NULL ,
location TEXT,
gender TEXT,
keywords TEXT,
creativity  INTEGER  DEFAULT 0,
completeness INTEGER  DEFAULT 0,
correctness INTEGER   DEFAULT 0,
readability  INTEGER  DEFAULT 0 ,
user_interface INTEGER DEFAULT 0  ,
download_count INTEGER  DEFAULT 0,
image_file_path TEXT ,
timestamp DATETIME DEFAULT CURRENT_TIMESTAMP );
